// <auto-generated />
namespace CharacterBuilder.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADDED_BG_TO_LANGUAGE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDED_BG_TO_LANGUAGE));
        
        string IMigrationMetadata.Id
        {
            get { return "201703022027082_ADDED_BG_TO_LANGUAGE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
