// <auto-generated />
namespace CharacterBuilder.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class POINT_SHEET_AT_APPLICATIONUSER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(POINT_SHEET_AT_APPLICATIONUSER));
        
        string IMigrationMetadata.Id
        {
            get { return "201703041458498_POINT_SHEET_AT_APPLICATIONUSER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
