// <auto-generated />
namespace CharacterBuilder.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Corrected_ScoreIncrease_OnSheet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Corrected_ScoreIncrease_OnSheet));
        
        string IMigrationMetadata.Id
        {
            get { return "201703091133151_Corrected_ScoreIncrease_OnSheet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
