// <auto-generated />
namespace CharacterBuilder.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class REMOVE_BG_FROM_OPTION : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(REMOVE_BG_FROM_OPTION));
        
        string IMigrationMetadata.Id
        {
            get { return "201703021803099_REMOVE_BG_FROM_OPTION"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
