// <auto-generated />
namespace CharacterBuilder.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CLASS_FIX_PROFICIENCYKEY : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CLASS_FIX_PROFICIENCYKEY));
        
        string IMigrationMetadata.Id
        {
            get { return "201703020024381_CLASS_FIX_PROFICIENCYKEY"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
