// <auto-generated />
namespace CharacterBuilder.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADDED_VARIANT_AND_LANGUAGE_TO_BACKGROUND : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDED_VARIANT_AND_LANGUAGE_TO_BACKGROUND));
        
        string IMigrationMetadata.Id
        {
            get { return "201703022025347_ADDED_VARIANT_AND_LANGUAGE_TO_BACKGROUND"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
