// <auto-generated />
namespace CharacterBuilder.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ARMOR_AND_WEAPON_CONTROLLERS_REPOS_CONTEXT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ARMOR_AND_WEAPON_CONTROLLERS_REPOS_CONTEXT));
        
        string IMigrationMetadata.Id
        {
            get { return "201703010100152_ARMOR_AND_WEAPON_CONTROLLERS_REPOS_CONTEXT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
