// <auto-generated />
namespace CharacterBuilder.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SOMETHING_CHANGED_NOTSUREWHAT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SOMETHING_CHANGED_NOTSUREWHAT));
        
        string IMigrationMetadata.Id
        {
            get { return "201703020127132_SOMETHING_CHANGED_NOTSUREWHAT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
